site_name: Audulus
nav:
    - Getting Started: index.md
    - Nodes Reference: nodes.md

# Repository
repo_name: 'audulus/docs'
repo_url: 'https://github.com/audulus/docs'

theme: 'readthedocs' 
extra:
  logo: 'img/Audulus_logo.svg'
